import {type User} from './types';

export const usersMock: User[] = [
  {
    iri: '/api/staff/1000',
    id: 1,
    fullName: 'Full name',
    displayName: 'User name',
    initials: 'UN',
    email: 'user.name@venue.nl',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: '//i.pravatar.cc/32?img=67',
    address: null,
    isEmployee: true,
    functionName: '1st Chef',
    userPermissions: []
  },
  {
    iri: '/api/staff/1000',
    id: 2,
    fullName: 'Full name',
    displayName: 'User name',
    initials: 'UN',
    email: 'user.name@venue.nl',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: '//i.pravatar.cc/32?img=59',
    address: null,
    isEmployee: true,
    functionName: '1st Chef',
    userPermissions: []
  },
  {
    iri: '/api/staff/1000',
    id: 3,
    fullName: 'Full name',
    displayName: 'User name',
    initials: 'UN',
    email: 'user.name@venue.nl',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: '//i.pravatar.cc/32?img=55',
    address: null,
    isEmployee: true,
    functionName: '1st Chef',
    userPermissions: []
  },
  {
    iri: '/api/staff/1000',
    id: 4,
    fullName: 'Full name',
    displayName: 'User name',
    initials: 'UN',
    email: 'user.name@venue.nl',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: '//i.pravatar.cc/32?img=67',
    address: null,
    isEmployee: true,
    functionName: '1st Chef',
    userPermissions: []
  },
  {
    iri: '/api/staff/1000',
    id: 5,
    fullName: 'Full name',
    displayName: 'User name',
    initials: 'UN',
    email: 'user.name@venue.nl',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: '//i.pravatar.cc/32?img=59',
    address: null,
    isEmployee: true,
    functionName: '1st Chef',
    userPermissions: []
  }
]
